---
network_file: /etc/sysconfig/network-scripts/ifcfg-eth0
dns_domain: "{{ lookup('env', 'CLOUD_DOMAIN')|default('example.com') }}"
        # FIXME getting the DNS server IP address
dns_server: "{{ hostvars['dns.example.com'].openshift.common.ip }}"
rh_user: "{{ lookup('env', 'RH_USERNAME') }}"
rh_pass: "{{ lookup('env', 'RH_PASSWORD') }}"
rh_pool: "{{ lookup('env', 'RH_POOL_ID') }}"
